package dev.gokce.payments.payment.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import jakarta.persistence.PostLoad
import jakarta.persistence.PostPersist
import jakarta.persistence.Table
import jakarta.persistence.Transient
import org.springframework.data.domain.Persistable
import java.time.Instant
import java.util.UUID

/**
 * One domain event, waiting to be published.
 *
 * The id is assigned here rather than generated by the database because it is also the event id
 * carried in the payload and in the Kafka header -- the value consumers deduplicate on. That forces
 * the [Persistable] dance below: with an assigned id, Spring Data cannot tell a new entity from a
 * detached one, so `save()` would issue a pointless SELECT before every INSERT.
 */
@Entity
@Table(name = "outbox_events")
class OutboxEvent(
    @Id
    private val id: UUID,

    /** Kafka message key: every event for one payment lands on one partition, in order. */
    @Column(name = "aggregate_id", nullable = false)
    val aggregateId: UUID,

    @Column(name = "aggregate_type", nullable = false, length = 32)
    val aggregateType: String,

    @Enumerated(EnumType.STRING)
    @Column(name = "event_type", nullable = false, length = 64)
    val eventType: PaymentEventType,

    @Column(nullable = false)
    val payload: String,
) : Persistable<UUID> {

    @Column(name = "occurred_at", nullable = false, updatable = false)
    val occurredAt: Instant = Instant.now()

    @Column(name = "published_at")
    var publishedAt: Instant? = null
        private set

    @Column(nullable = false)
    var attempts: Int = 0
        private set

    @Column(name = "last_error", length = 500)
    var lastError: String? = null
        private set

    @Transient
    private var unsaved = true

    override fun getId(): UUID = id

    override fun isNew(): Boolean = unsaved

    @PostPersist
    @PostLoad
    fun markStored() {
        unsaved = false
    }

    /** Called only after the broker has acknowledged the record. */
    fun markPublished() {
        publishedAt = Instant.now()
        lastError = null
    }

    fun recordFailure(reason: String?) {
        attempts += 1
        lastError = reason?.take(500)
    }
}
