-- Double-entry ledger.
--
-- ledger_entries is the append-only source of truth. Every movement of money writes one DEBIT
-- row and one CREDIT row that share a transfer_id, inside a single database transaction.
-- accounts.balance is a cache of that stream, written in the same transaction, so a balance read
-- costs one row lookup instead of an aggregate over the whole history.

CREATE TABLE accounts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name   VARCHAR(200) NOT NULL,
    currency     VARCHAR(3)   NOT NULL,
    account_type VARCHAR(16)  NOT NULL,
    balance      BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT accounts_owner_name_not_blank CHECK (length(btrim(owner_name)) > 0),
    CONSTRAINT accounts_currency_iso4217 CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT accounts_type_known CHECK (account_type IN ('CUSTOMER', 'SYSTEM')),

    -- A customer account may never go negative, and the database is the last line of defence:
    -- even a bug in the service cannot commit an overdrawn customer balance.
    -- The SYSTEM account is the counterparty for deposits and is *expected* to be negative --
    -- it represents money that has entered the ledger from outside.
    CONSTRAINT accounts_customer_balance_non_negative
        CHECK (account_type = 'SYSTEM' OR balance >= 0)
);

-- Exactly one funding account per currency. Looked up by (type, currency) rather than by a
-- hardcoded id, so nothing in the code depends on a magic primary key value.
CREATE UNIQUE INDEX accounts_one_system_account_per_currency
    ON accounts (currency) WHERE account_type = 'SYSTEM';

CREATE TABLE ledger_entries
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT      NOT NULL REFERENCES accounts (id),
    transfer_id UUID        NOT NULL,
    direction   VARCHAR(6)  NOT NULL,
    amount      BIGINT      NOT NULL,
    currency    VARCHAR(3)  NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Amounts are always positive; the sign lives in `direction`. Signed amounts invite
    -- sign-confusion bugs and make "total credited" queries ambiguous.
    CONSTRAINT ledger_entries_amount_positive CHECK (amount > 0),
    CONSTRAINT ledger_entries_direction_known CHECK (direction IN ('DEBIT', 'CREDIT')),

    -- One row per (transfer, account, side). This constraint is what makes a replayed transfer
    -- impossible to post twice, even if two requests race.
    CONSTRAINT ledger_entries_one_row_per_side UNIQUE (transfer_id, account_id, direction)
);

-- Serves GET /accounts/{id}/entries, newest first.
CREATE INDEX ledger_entries_by_account ON ledger_entries (account_id, id DESC);

-- The ledger is append-only. Correcting a mistake means posting a reversing entry, never
-- rewriting history: an audit trail you can edit is not an audit trail.
CREATE FUNCTION ledger_entries_forbid_mutation() RETURNS TRIGGER AS
$$
BEGIN
    RAISE EXCEPTION 'ledger_entries is append-only (attempted %)', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ledger_entries_append_only
    BEFORE UPDATE OR DELETE
    ON ledger_entries
    FOR EACH ROW
EXECUTE FUNCTION ledger_entries_forbid_mutation();

-- Funding counterparty for EUR deposits. Supporting another currency is one INSERT in a new
-- migration, not a code change.
INSERT INTO accounts (owner_name, currency, account_type)
VALUES ('System funding account (EUR)', 'EUR', 'SYSTEM');
